// programa para saber que tipo de triangulo es 

int lado1 = 5;
int lado2 = 5;
string lado3 = 5;  // tipo equivocado de dato 

if ( lado1 == lado2 and lado1 == lado3){
  input ("EL_TRIANGULO_ES_EQUILATERO");
} 

if (lado1 == lado2 and lado1 != lado3){
 input("EL_TRIANGULO_ES_ISOSELES");
 } 

if (lado1 != lado2 and lado1 != lado3 and lado2 != lado3){
 input("EL_TRIANGULO_ES_ESCALENO"); // falta la llave de cierre }
